name: assignment_tracker
description: A teacher assignment tracker app (local storage, modern UI)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  lottie: ^2.3.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
